### PR TITLE
Submission/ pull request for hw1

### PR DESCRIPTION
**Pull request by mattadlerpdx**
This PR is code for FizzBuzz, hw1 for the fullstack class. I changed the order of logic so that 'fizzbuzz' prints. I also followed airBnB guidelines for JS (=== vs ==). Please let me know of any syntax issues/JS styles I might be missing.

### CODE REVIEW

**Review by JeremiahTilse — COMMENTED** [review]
Looks good, but I have a few suggestions:

- Use an auto-formatter, such as Prettier in VS Code.  It will fix many style issues, particularly inconsistencies with line breaks, tabs, and spacing.  See [16.2](https://github.com/airbnb/javascript#blocks--cuddled-elses), [19.1](https://github.com/airbnb/javascript#whitespace--spaces), [19.2](https://github.com/airbnb/javascript#whitespace--before-blocks), [19.3](https://github.com/airbnb/javascript#whitespace--around-keywords), and [19.4](https://github.com/airbnb/javascript#whitespace--infix-ops), in the Airbnb Style Guide.  In my last class on web-dev, I didn't have Prettier setup properly at first and it was not working.  You may want to play with it a bit to make sure it is correcting on save.  I have mine set to add "@format" to the top so I can tell when it has formatted the file.

- Also avoid using increments.  See [13.6](https://github.com/airbnb/javascript#variables--unary-increment-decrement), in the same guide.

Good work!

Edit:  Just noticed that the for loop is a little difficult to read to make sure the logic is correct.  It looks like it works but `for (i = 1; i <= 100; i += 1) {...}` will be easier to read.

Edit: Just tested it and it fires for 0 and not for 100.

**Comment by C3ra906** [comment]
Hi Matt, 

I think you should use let when declaring variable i in the for loop and start with 1 as the value instead of 0. I believe 0 % 3 and 0 % 5 are equal to 0 and that may print 'fizzbuzz' for i = 0. Also, i should end when i < 101 or i <=100 since we want 1 to 100 inclusive. You should keep the spacing between things consistent for easier readability. I agree with Jeremiah that you should turn on Prettier if you haven't - it has helped me a lot in Intro to Full Stack! Otherwise your code looks great, good job!

**Review by C3ra906 — CHANGES_REQUESTED** [review]
Hi Matt,

I think you should use let when declaring variable i in the for loop and start with 1 as the value instead of 0. I believe 0 % 3 and 0 % 5 are equal to 0 and that may print 'fizzbuzz' for i = 0. Also, i should end when i < 101 or i <=100 since we want 1 to 100 inclusive. 

You should keep the spacing between things consistent for easier readability. I agree with Jeremiah that you should turn on Prettier if you haven't - it has helped me a lot in Intro to Full Stack! 

Otherwise your code looks great, good job!

**Comment by Alvin-PDX** [comment]
Matt, your code is solid; here are my suggestions:

- Double check the for loop so that it increments all the way to 100. 
- Try using consistent spacing
- The AirBnB style guide recommends only using single quotes for strings, and not using ++ for incrementing (so i += 1 instead.)

**Pull request merged**
